# Generated by Django 4.2.5 on 2023-10-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="название"),
                ),
                (
                    "slug",
                    models.CharField(max_length=100, verbose_name="slug"),
                ),
                ("body", models.TextField(verbose_name="описание")),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="product/",
                        verbose_name="превью",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата"
                    ),
                ),
                ("published", models.BooleanField(verbose_name="статус")),
                ("counter_views", models.IntegerField(verbose_name="счетчик")),
            ],
            options={
                "verbose_name": "материал",
                "verbose_name_plural": "материалы",
            },
        ),
    ]
