# Generated by Django 4.2.5 on 2023-10-08 21:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="date_creation",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="дата"
            ),
        ),
    ]
