# Generated by Django 4.2.6 on 2023-10-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="number_of_views",
        ),
        migrations.AddField(
            model_name="post",
            name="count_views",
            field=models.IntegerField(default=0, verbose_name="Количество просмотров"),
        ),
        migrations.AddField(
            model_name="post",
            name="publication_sign",
            field=models.BooleanField(default=True, verbose_name="Признак публикации"),
        ),
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Slug"
            ),
        ),
    ]
