# Generated by Django 4.2.6 on 2023-10-28 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0003_alter_post_date_of_creation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date_of_creation",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Дата создания",
            ),
        ),
    ]
