# Generated by Django 4.2.6 on 2023-10-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0005_alter_post_date_of_creation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date_of_creation",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата создания"
            ),
        ),
    ]
